server:
  port: 8085
  
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    showSql: true                        # jpa가 실행하는 쿼리를 console 로그로 출력하기 위한 설정
    hibernate.ddl-auto: update           # 시작하면서 도메인 객체 구성과 DB의 스키마를 비교해
                                         # 필요한 테이블이나 컬럼이 없을 때 도메인 객체에 맞춰 DB 스키마를 변경
  messages:
    basename: i18n/exception
    encoding: UTF-8
    
---                  
logging:
  level:
    org:
      springframework: debug
---
logging:
  level:
    org:
      springframework:
        web: debug